"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

import dj_database_url
from corsheaders.defaults import default_headers
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'DJANGO_SECRET_KEY',
    'django-insecure-@1wcmg2$li9x1ql4m2601%rwe$8r%c%t7qymf#*^6)i78f4v-x',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [h for h in os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'contests',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    o for o in os.getenv(
        'CORS_ALLOWED_ORIGINS',
        'http://localhost:5173,http://127.0.0.1:5173',
    ).split(',') if o
]

# 스코어보드가 조건부 요청(If-None-Match → 304)을 쓰려면 CORS 양쪽을 다 열어야 한다.
# - 응답의 ETag 를 자바스크립트가 읽을 수 있어야 하고(기본은 안전 목록 헤더만 노출),
# - 요청의 If-None-Match 가 프리플라이트에서 허용돼야 한다. django-cors-headers 의 기본
#   허용 목록에는 If-None-Match 가 없어서, 빼먹으면 프리플라이트가 통과해도 브라우저가
#   본 요청 자체를 보내지 않는다(서버 로그에는 OPTIONS 만 남아 원인이 잘 안 보인다).
CORS_EXPOSE_HEADERS = ['ETag']
CORS_ALLOW_HEADERS = (*default_headers, 'if-none-match')

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

if os.getenv('DATABASE_URL'):
    # Render/Railway/Supabase 는 관리형 DB 를 단일 연결 문자열로 넘겨준다.
    #
    # Supabase 는 Supavisor 풀러(aws-*.pooler.supabase.com) 뒤에 있으므로 Django
    # 쪽 영속 연결을 끈다(conn_max_age=0). 풀러가 이미 연결을 재사용하고 있어서,
    # Django 가 붙들고 있는 유휴 연결은 풀 슬롯만 차지하다 서버 쪽에서 끊기고
    # 다음 요청에서 InterfaceError 로 터진다.
    #
    # 풀러는 세션 모드(포트 5432)를 전제로 한다 - 일반 Postgres 와 동작이 같아
    # migrate 와 서버 사이드 커서가 그대로 돈다. 트랜잭션 모드(6543)로 바꾸려면
    # disable_server_side_cursors=True 가 함께 필요하다.
    DATABASES = {'default': dj_database_url.parse(
        os.environ['DATABASE_URL'],
        conn_max_age=0,
        ssl_require=True,
    )}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('POSTGRES_DB', 'webclaude'),
            'USER': os.getenv('POSTGRES_USER', 'webclaude'),
            'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'webclaude'),
            'HOST': os.getenv('POSTGRES_HOST', 'localhost'),
            'PORT': os.getenv('POSTGRES_PORT', '5432'),
        }
    }


# Cache
# https://docs.djangoproject.com/en/6.1/topics/cache/
#
# 프로세스 메모리 캐시. 스코어보드 집계(5초 폴링 × 접속자 수)와 GitHub 프록시 응답을 담는
# 용도라 Redis 를 따로 붙이지 않는다 — Render 는 gunicorn 워커 1개로 돌리므로 프로세스가
# 하나뿐이고, 캐시가 비어도 원본을 다시 계산하면 그만인 데이터만 넣는다. 워커를 여러 개로
# 늘리면 워커마다 캐시가 따로 생겨 무효화가 자기 워커에만 걸린다(최대 TTL 만큼 지연).

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'hackman-local',
    }
}

# 스코어보드 집계 캐시 수명(초). 점수·팀·제출물이 바뀌면 즉시 무효화되므로, 이 값은
# "아무도 쓰지 않는 동안 같은 집계를 몇 초까지 재사용할지"만 정한다.
SCOREBOARD_CACHE_SECONDS = int(os.getenv('SCOREBOARD_CACHE_SECONDS', '3'))

# GitHub 심사 도구 프록시.
# 토큰이 없으면 비인증(시간당 60회)으로 동작하고, 있으면 시간당 5000회로 올라간다.
# public_repo 조차 필요 없는 읽기 전용 fine-grained 토큰이면 충분하다.
GITHUB_TOKEN = os.getenv('GITHUB_TOKEN', '')
# 저장소 트리·파일은 심사 중에 거의 바뀌지 않고 같은 저장소를 심사위원 여러 명이 반복해서
# 연다. 캐시 적중이 rate limit 을 지키는 주된 수단이다.
GITHUB_CACHE_SECONDS = int(os.getenv('GITHUB_CACHE_SECONDS', '1800'))

# LLM 제공사 키. 셋 다 선택이고, 설정된 것만 모델 선택기에 노출된다(`contests/llm/base.py`).
# 하나도 없으면 LLM 기능만 꺼지고 나머지는 그대로 동작한다 — 팀빌딩 추천 순위는 규칙 기반이라
# 키 없이도 계산된다.
ANTHROPIC_API_KEY = os.getenv('ANTHROPIC_API_KEY', '')
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', '')
GOOGLE_API_KEY = os.getenv('GOOGLE_API_KEY', '')


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}


# Django REST Framework
# https://www.django-rest-framework.org/api-guide/settings/

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=2),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=14),
}


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
