# Generated by Django 6.1 on 2026-09-08 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_remove_contest_presentation_start_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField(blank=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('roles', models.JSONField(blank=True, default=list)),
                ('level', models.CharField(blank=True, choices=[('beginner', '입문'), ('intermediate', '중급'), ('advanced', '숙련')], default='', max_length=20)),
                ('looking_for_team', models.BooleanField(default=True)),
                ('extraction_status', models.CharField(choices=[('empty', '추출 안 함'), ('pending', '추출 대기'), ('done', '추출 완료'), ('failed', '추출 실패')], default='empty', max_length=20)),
                ('extraction_error', models.TextField(blank=True)),
                ('extracted_by', models.CharField(blank=True, default='', max_length=80)),
                ('extracted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
