# Generated by Django 6.1 on 2026-09-11 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0007_profile_github_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('slug', models.SlugField(max_length=60, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('category', models.CharField(choices=[('language', '언어'), ('framework', '프레임워크·라이브러리'), ('tool', '도구·인프라')], default='language', max_length=20)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='other_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='SubmissionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('pending', '분석 중'), ('done', '분석 완료'), ('failed', '분석 실패')], default='pending', max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('findings', models.JSONField(blank=True, default=list)),
                ('cited_paths', models.JSONField(blank=True, default=list)),
                ('stack', models.JSONField(blank=True, default=list)),
                ('truncated', models.BooleanField(default=False)),
                ('files_read', models.PositiveIntegerField(default=0)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('submission_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='contests.submission')),
            ],
            options={
                'ordering': ['provider', 'model'],
                'unique_together': {('submission', 'provider', 'model')},
            },
        ),
    ]
