-- 정규 기술 스택 시드. backend/contests/tech_stacks.py 의 SEED 와 같은 목록이다.
-- 시드일 뿐 정본은 이 테이블이고, 운영자가 Studio 에서 고친다. 되돌려도 지우지 않는다.
insert into public.tech_stacks (slug, name, category, aliases) values
  ('javascript', 'JavaScript', 'language', array['js', '자바스크립트']),
  ('typescript', 'TypeScript', 'language', array['ts', '타입스크립트']),
  ('python', 'Python', 'language', array['파이썬', 'py']),
  ('java', 'Java', 'language', array['자바']),
  ('c', 'C', 'language', '{}'),
  ('cpp', 'C++', 'language', array['c++', 'cplusplus', '씨쁠쁠']),
  ('csharp', 'C#', 'language', array['c#', 'c sharp', '씨샵']),
  ('go', 'Go', 'language', array['golang', '고랭']),
  ('rust', 'Rust', 'language', array['러스트']),
  ('kotlin', 'Kotlin', 'language', array['코틀린']),
  ('swift', 'Swift', 'language', array['스위프트']),
  ('objective-c', 'Objective-C', 'language', array['objc', 'objective c']),
  ('ruby', 'Ruby', 'language', array['루비']),
  ('php', 'PHP', 'language', '{}'),
  ('dart', 'Dart', 'language', array['다트']),
  ('scala', 'Scala', 'language', '{}'),
  ('r', 'R', 'language', '{}'),
  ('matlab', 'MATLAB', 'language', array['매트랩']),
  ('shell', 'Shell', 'language', array['bash', 'sh', '셸', '쉘스크립트']),
  ('powershell', 'PowerShell', 'language', '{}'),
  ('lua', 'Lua', 'language', '{}'),
  ('perl', 'Perl', 'language', '{}'),
  ('haskell', 'Haskell', 'language', '{}'),
  ('elixir', 'Elixir', 'language', '{}'),
  ('erlang', 'Erlang', 'language', '{}'),
  ('clojure', 'Clojure', 'language', '{}'),
  ('julia', 'Julia', 'language', '{}'),
  ('groovy', 'Groovy', 'language', '{}'),
  ('solidity', 'Solidity', 'language', array['솔리디티']),
  ('assembly', 'Assembly', 'language', array['어셈블리']),
  ('html', 'HTML', 'language', array['html5']),
  ('css', 'CSS', 'language', array['css3']),
  ('scss', 'SCSS', 'language', array['sass']),
  ('sql', 'SQL', 'language', '{}'),
  ('jupyter-notebook', 'Jupyter Notebook', 'language', array['jupyter', '주피터']),
  ('zig', 'Zig', 'language', '{}'),
  ('verilog', 'Verilog', 'language', '{}'),
  ('react', 'React', 'framework', array['react.js', 'reactjs', '리액트']),
  ('nextjs', 'Next.js', 'framework', array['next', 'next.js', '넥스트']),
  ('vue', 'Vue.js', 'framework', array['vue.js', 'vuejs', '뷰']),
  ('nuxt', 'Nuxt', 'framework', array['nuxt.js', 'nuxtjs']),
  ('angular', 'Angular', 'framework', array['angular.js', '앵귤러']),
  ('svelte', 'Svelte', 'framework', array['sveltekit', '스벨트']),
  ('nodejs', 'Node.js', 'framework', array['node', 'node.js', '노드']),
  ('express', 'Express', 'framework', array['express.js', 'expressjs']),
  ('nestjs', 'NestJS', 'framework', array['nest', 'nest.js']),
  ('django', 'Django', 'framework', array['장고']),
  ('drf', 'Django REST Framework', 'framework', array['django rest framework', 'django-rest-framework']),
  ('flask', 'Flask', 'framework', array['플라스크']),
  ('fastapi', 'FastAPI', 'framework', array['fast api']),
  ('spring-boot', 'Spring Boot', 'framework', array['spring', 'springboot', '스프링']),
  ('rails', 'Ruby on Rails', 'framework', array['ruby on rails', 'rails']),
  ('laravel', 'Laravel', 'framework', array['라라벨']),
  ('aspnet', 'ASP.NET', 'framework', array['asp.net', 'dotnet', '.net']),
  ('flutter', 'Flutter', 'framework', array['플러터']),
  ('react-native', 'React Native', 'framework', array['react native', 'rn']),
  ('swiftui', 'SwiftUI', 'framework', array['swift ui']),
  ('jetpack-compose', 'Jetpack Compose', 'framework', array['compose', 'jetpack compose']),
  ('android', 'Android', 'framework', array['안드로이드']),
  ('electron', 'Electron', 'framework', '{}'),
  ('tailwindcss', 'Tailwind CSS', 'framework', array['tailwind', 'tailwind css']),
  ('bootstrap', 'Bootstrap', 'framework', array['부트스트랩']),
  ('jquery', 'jQuery', 'framework', array['제이쿼리']),
  ('threejs', 'Three.js', 'framework', array['three.js', 'three']),
  ('unity', 'Unity', 'framework', array['유니티']),
  ('unreal-engine', 'Unreal Engine', 'framework', array['unreal', '언리얼']),
  ('tensorflow', 'TensorFlow', 'framework', array['tf', '텐서플로우', '텐서플로']),
  ('pytorch', 'PyTorch', 'framework', array['torch', '파이토치']),
  ('scikit-learn', 'scikit-learn', 'framework', array['sklearn', 'scikit learn']),
  ('pandas', 'pandas', 'framework', array['판다스']),
  ('numpy', 'NumPy', 'framework', array['넘파이']),
  ('opencv', 'OpenCV', 'framework', array['cv2', '오픈씨브이']),
  ('langchain', 'LangChain', 'framework', array['랭체인']),
  ('huggingface', 'Hugging Face', 'framework', array['hugging face', 'transformers', '허깅페이스']),
  ('streamlit', 'Streamlit', 'framework', array['스트림릿']),
  ('gradio', 'Gradio', 'framework', '{}'),
  ('openai-api', 'OpenAI API', 'framework', array['openai', 'gpt', 'chatgpt api']),
  ('vite', 'Vite', 'framework', array['비트']),
  ('webpack', 'Webpack', 'framework', '{}'),
  ('redux', 'Redux', 'framework', array['리덕스']),
  ('graphql', 'GraphQL', 'framework', array['그래프큐엘']),
  ('prisma', 'Prisma', 'framework', '{}'),
  ('sqlalchemy', 'SQLAlchemy', 'framework', '{}'),
  ('socketio', 'Socket.IO', 'framework', array['socket.io', 'websocket', '웹소켓']),
  ('git', 'Git', 'tool', array['깃']),
  ('github-actions', 'GitHub Actions', 'tool', array['github action', 'gh actions', '깃허브 액션']),
  ('docker', 'Docker', 'tool', array['도커']),
  ('kubernetes', 'Kubernetes', 'tool', array['k8s', '쿠버네티스']),
  ('aws', 'AWS', 'tool', array['amazon web services', 'ec2', 's3', '아마존']),
  ('gcp', 'Google Cloud', 'tool', array['google cloud platform', 'gcp']),
  ('azure', 'Azure', 'tool', array['microsoft azure']),
  ('firebase', 'Firebase', 'tool', array['파이어베이스']),
  ('supabase', 'Supabase', 'tool', array['수파베이스']),
  ('vercel', 'Vercel', 'tool', array['버셀']),
  ('netlify', 'Netlify', 'tool', '{}'),
  ('render', 'Render', 'tool', '{}'),
  ('postgresql', 'PostgreSQL', 'tool', array['postgres', 'psql', '포스트그레스']),
  ('mysql', 'MySQL', 'tool', array['마리아디비', 'mariadb']),
  ('mongodb', 'MongoDB', 'tool', array['mongo', '몽고디비']),
  ('redis', 'Redis', 'tool', array['레디스']),
  ('sqlite', 'SQLite', 'tool', '{}'),
  ('elasticsearch', 'Elasticsearch', 'tool', array['elastic search']),
  ('nginx', 'Nginx', 'tool', '{}'),
  ('linux', 'Linux', 'tool', array['ubuntu', '리눅스', '우분투']),
  ('figma', 'Figma', 'tool', array['피그마']),
  ('postman', 'Postman', 'tool', array['포스트맨']),
  ('notion', 'Notion', 'tool', array['노션']),
  ('jira', 'Jira', 'tool', array['지라']),
  ('jenkins', 'Jenkins', 'tool', array['젠킨스']),
  ('terraform', 'Terraform', 'tool', '{}'),
  ('kafka', 'Apache Kafka', 'tool', array['apache kafka', '카프카']),
  ('selenium', 'Selenium', 'tool', array['셀레니움']),
  ('jest', 'Jest', 'tool', '{}'),
  ('pytest', 'pytest', 'tool', '{}'),
  ('cypress', 'Cypress', 'tool', '{}'),
  ('arduino', 'Arduino', 'tool', array['아두이노']),
  ('raspberry-pi', 'Raspberry Pi', 'tool', array['raspberry pi', '라즈베리파이']),
  ('blender', 'Blender', 'tool', array['블렌더']),
  ('photoshop', 'Photoshop', 'tool', array['포토샵', 'adobe photoshop']),
  ('illustrator', 'Illustrator', 'tool', array['일러스트레이터'])
on conflict (slug) do nothing;
